target-version = "py39"
line-length = 100

[lint]
select = [
  "E",
  "F",
  "I",
  "B",
  "UP",
  "N",
]
ignore = ["E501"]

[lint.isort]
known-first-party = ["langchain_notion_tools"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
