name: CI

on:
  push:
    branches:
      - main
      - feature/notion-write-toolkit
  pull_request:

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-lint-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'ruff.toml') }}
          restore-keys: |
            pip-lint-${{ runner.os }}-
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run Ruff
        run: ruff check .

  type-check:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-mypy-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'mypy.ini') }}
          restore-keys: |
            pip-mypy-${{ runner.os }}-
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run mypy
        run: mypy src

  test:
    name: Pytest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-test-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-test-${{ runner.os }}-${{ matrix.python-version }}-
            pip-test-${{ runner.os }}-
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run tests
        run: pytest
